version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: realtorsite_postgres_dev
    environment:
      POSTGRES_DB: realtorsite
      POSTGRES_USER: realtorsite_user
      POSTGRES_PASSWORD: realtorsite_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realtorsite_user -d realtorsite"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: realtorsite_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: realtorsite_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@realtorsite.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 