services:
  postgres:
    image: postgres:15-alpine
    container_name: realtorsite_postgres
    environment:
      POSTGRES_DB: realtorsite
      POSTGRES_USER: realtorsite_user
      POSTGRES_PASSWORD: realtorsite_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: realtorsite_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: realtorsite_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@realtorsite.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 